### ISSUE TITLE
Docker cannot run ros command from outside

### ISSUE THREAD

**Issue by weber-niklas** [turag-ev/EB23#49]
After setting up a pi, we tried launching our bot remotely after already ssh'ing via:

```bash
sudo docker exec -it EB23 bash -c "cd workspace && ros2 launch bringup BotA_launch.py teamcolor:=Blue strategy:=Test fb_baudrate:=500000 fb_device:=/dev/ttyUSB0"
```
However, we get the error that the command ros2 is unkown:
```bash
bash: ros2: command not found
```

This
```bash
sudo docker exec -it EB23 bash -c "cd workspace&&ls"
```
works perfectly fine

Maybe someone can help fixing this? Surely we do not need ros2 outside of the container

**Comment by Zarnack** [comment]
Two things:

[1. Please follow these steps so you do not have to use sudo.](https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user)
2. The described problem occurs because you are not sourcing your workspace:

Why are you not sourcing your workspace, even though everything is in the .bashrc/.zshrc?

Those files are never fully evaluated when you are trying to execute a script or such a command because of this default line at the top of every ./bashrc:
```
# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac
```
When you are executing a script or simply bash -c "ros2" you are not running in an interactive mode.

To fix this issue you could either execute the bash command in interactive mode by adding the -i argument:

`docker exec -it EB23 bash -i -c "cd workspace && ros2 launch bringup BotA_launch.py teamcolor:=Blue strategy:=Test fb_baudrate:=500000 fb_device:=/dev/ttyUSB0"`

Or source the bashrc before executing the command:

`docker exec -it EB23 bash -c "source ~/.bashrc && cd workspace && ros2 launch bringup BotA_launch.py teamcolor:=Blue strategy:=Test fb_baudrate:=500000 fb_device:=/dev/ttyUSB0"`

**Comment by weber-niklas** [comment]
Thank you for clarifying <3 Will try this when I am back at the lab

**Comment by weber-niklas** [comment]
works now. thanks for the help
